#!/usr/bin/python3

import logging
import traceback
import os.path

from src.View import Interface

if os.path.isfile('ir.log'):
    os.remove('ir.log')

logging.basicConfig(filename='ir.log', level=logging.DEBUG, format='(%(asctime)s) %(message)s', datefmt='%I:%M:%S')
logging.debug("Intelligent Reader started")

try:
    interface = Interface()
    interface.run()
except BaseException as e:
    logging.critical(traceback.format_exc())

