#!/usr/bin/python3
import IrLoad
import IrLearn
import os
from UserInterface import UserInterface

def main():
	#Load Data completely if nothing else exists
	if not os.path.exists("database"): 
		IrLoad.loadData()
	else:
		print("Data already exists")
	interface = UserInterface()
	interface.process()
	IrLearn.learnData()
	interface.show()

if __name__ == "__main__":
	main()